<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hool_help()
 */

function marca_favorita_help($route_name, RouteMatchInterface $route_match){
    switch($route_name){
        case 'help.page.marca_favorita':
            return t('
                <h3>Acerca</h3>
                <p>Campo Marca Favorita</p>
            ');
    }
}


/**
 * Implements hook_theme().
 */
function marca_favorita_theme() {
  return [
    'marca_favorita' => [
        'variables' => [
            'title' => '',
            'description' => ''
        ],
        "template" => 'marca_favorita'
    ]
  ];
}
